### ISSUE TITLE
Publish a new patch to make the RunKit example available

### ISSUE THREAD

**Issue by EndBug** [fatchan/overwatch-stats-api#7]
In order for #6 to have an effect you'll need to `npm version patch && npm publish` the package. I forgot to include it in the PR

_Side note: sorry, I know I'm bugging you but I may open more PRs in the near future since I need some stuff for a project. If that's fine for you it's ok, otherwise, you can add me as GitHub/npm collaborator if you want to_

**Comment by fatchan** [comment]
I literally pressed enter on npm publish and jumped into bed, didn't check the terminal. Then github email rings my phone, wakes me up. All good because... I didn't enter my fucking OTP so it was just sitting there waiting :joy:

Also I'll add you as a collaborator since you seem pretty active, and are probably the only person interested in adding typings for when the new hero starts showing up on stat pages.
